from PyQt5 import QtWidgets, QtGui, QtCore
from input import Ui_Modifier


class myinput(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(myinput, self).__init__(parent=parent)
        self.ui = Ui_Modifier()
        self.ui.setupUi(self)
        self.ui.lineEdit.setText("0")
        self.ui.lineEdit_2.setText("0")
        self.ui.lineEdit_3.setText("0")
        self.ui.lineEdit_4.setText("0")
        self.ui.lineEdit_5.setText("0")
        self.ui.lineEdit_6.setText("0")
        self.ui.lineEdit_7.setText("0")
        self.ui.lineEdit_8.setText("0")
        self.ui.lineEdit_9.setText("0")
        self.ui.lineEdit_10.setText("0")
        self.ui.lineEdit_11.setText("0")
        self.ui.lineEdit_12.setText("0")
        self.ui.lineEdit_13.setText("0")
        self.ui.lineEdit_14.setText("0")
        self.ui.lineEdit_15.setText("0")
        self.ui.lineEdit_16.setText("0")
        self.ui.lineEdit_17.setText("0")
        self.ui.lineEdit_18.setText("0")
        self.ui.lineEdit_19.setText("0")
        self.ui.lineEdit_20.setText("0")
        self.ui.lineEdit_21.setText("0")
        self.ui.lineEdit_22.setText("0")
        self.ui.lineEdit_23.setText("0")
        self.ui.lineEdit_24.setText("0")
        self.ui.lineEdit_25.setText("0")
        self.ui.lineEdit_26.setText("0")
        self.ui.lineEdit_27.setText("0")
        self.ui.lineEdit_28.setText("0")
        self.ui.lineEdit_29.setText("0")
        self.ui.lineEdit_30.setText("0")
        self.ui.lineEdit_31.setText("0")
        self.ui.lineEdit_32.setText("0")
        self.ui.lineEdit_33.setText("0")
        self.ui.lineEdit_34.setText("0")
        self.ui.lineEdit_35.setText("0")
        self.ui.lineEdit_36.setText("0")
        self.ui.lineEdit_37.setText("0")
        self.ui.lineEdit_38.setText("0")
        self.ui.lineEdit_39.setText("0")
        self.ui.lineEdit_40.setText("0")
        self.ui.lineEdit_41.setText("0")
        self.ui.lineEdit_42.setText("0")
        self.ui.lineEdit_43.setText("0")
        self.ui.lineEdit_44.setText("0")
        self.ui.lineEdit_45.setText("0")
        self.ui.lineEdit_46.setText("0")
        self.ui.lineEdit_47.setText("0")
        self.ui.lineEdit_48.setText("0")
        self.ui.lineEdit_49.setText("0")
        self.ui.lineEdit_50.setText("0")
        self.ui.lineEdit_51.setText("0")
        self.ui.lineEdit_52.setText("0")
        self.ui.lineEdit_53.setText("0")
        self.ui.lineEdit_54.setText("0")
        self.ui.lineEdit_55.setText("0")
        self.ui.lineEdit_56.setText("0")
        self.ui.lineEdit_57.setText("0")
        self.ui.lineEdit_58.setText("0")
        self.ui.lineEdit_59.setText("0")
        self.ui.lineEdit_60.setText("0")
        self.ui.lineEdit_61.setText("0")
        self.ui.lineEdit_62.setText("0")
        self.ui.lineEdit_63.setText("0")
        self.ui.lineEdit_64.setText("0")
        self.ui.lineEdit_65.setText("0")
        self.ui.lineEdit_66.setText("0")
        self.ui.lineEdit_67.setText("0")
        self.ui.lineEdit_68.setText("0")
        self.ui.lineEdit_69.setText("0")
        self.ui.lineEdit_70.setText("0")
        self.ui.lineEdit_71.setText("0")
        self.ui.lineEdit_72.setText("0")
        self.ui.lineEdit_73.setText("0")
        self.ui.lineEdit_74.setText("0")
        self.ui.lineEdit_75.setText("0")
        self.ui.lineEdit_76.setText("0")
        self.ui.lineEdit_77.setText("0")
        self.ui.lineEdit_78.setText("0")
        self.ui.lineEdit_79.setText("0")
        self.ui.lineEdit_80.setText("0")
        self.ui.lineEdit_81.setText("0")

    # def closeEvent(self, QCloseEvent):
    #     self.main = mywindow()
