# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modifier(object):
    def setupUi(self, Modifier):
        Modifier.setObjectName("Modifier")
        Modifier.resize(640, 480)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Modifier)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 251, 241))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_66 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.gridLayout_2.addWidget(self.lineEdit_66, 7, 2, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_2.addWidget(self.lineEdit_42, 4, 5, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_2.addWidget(self.lineEdit_54, 5, 8, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_2.addWidget(self.lineEdit_44, 4, 7, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_2.addWidget(self.lineEdit_30, 3, 2, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_2.addWidget(self.lineEdit_31, 3, 3, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout_2.addWidget(self.lineEdit_61, 6, 6, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_2.addWidget(self.lineEdit_51, 5, 5, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_2.addWidget(self.lineEdit_21, 2, 2, 1, 1)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.gridLayout_2.addWidget(self.lineEdit_68, 7, 4, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_2.addWidget(self.lineEdit_23, 2, 4, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_2.addWidget(self.lineEdit_16, 1, 6, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_2.addWidget(self.lineEdit_19, 2, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_2.addWidget(self.lineEdit_27, 2, 8, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_2.addWidget(self.lineEdit_55, 6, 0, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout_2.addWidget(self.lineEdit_60, 6, 5, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_2.addWidget(self.lineEdit_49, 5, 3, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_2.addWidget(self.lineEdit_17, 1, 7, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_2.addWidget(self.lineEdit_53, 5, 7, 1, 1)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.gridLayout_2.addWidget(self.lineEdit_69, 7, 5, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_72 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.gridLayout_2.addWidget(self.lineEdit_72, 7, 8, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_2.addWidget(self.lineEdit_33, 3, 5, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_2.addWidget(self.lineEdit_45, 4, 8, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout_2.addWidget(self.lineEdit_62, 6, 7, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_2.addWidget(self.lineEdit_47, 5, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_2.addWidget(self.lineEdit_22, 2, 3, 1, 1)
        self.lineEdit_70 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.gridLayout_2.addWidget(self.lineEdit_70, 7, 6, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_2.addWidget(self.lineEdit_26, 2, 7, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_2.addWidget(self.lineEdit_15, 1, 5, 1, 1)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.gridLayout_2.addWidget(self.lineEdit_71, 7, 7, 1, 1)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.gridLayout_2.addWidget(self.lineEdit_67, 7, 3, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 2, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_2.addWidget(self.lineEdit_48, 5, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 0, 6, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_2.addWidget(self.lineEdit_25, 2, 6, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_2.addWidget(self.lineEdit_37, 4, 0, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_2.addWidget(self.lineEdit_29, 3, 1, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout_2.addWidget(self.lineEdit_63, 6, 8, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_2.addWidget(self.lineEdit_20, 2, 1, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_2.addWidget(self.lineEdit_34, 3, 6, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 0, 5, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_2.addWidget(self.lineEdit_50, 5, 4, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 0, 4, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_2.addWidget(self.lineEdit_28, 3, 0, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_2.addWidget(self.lineEdit_32, 3, 4, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_2.addWidget(self.lineEdit_38, 4, 1, 1, 1)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.gridLayout_2.addWidget(self.lineEdit_64, 7, 0, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_2.addWidget(self.lineEdit_57, 6, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 1, 3, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_2.addWidget(self.lineEdit_36, 3, 8, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_2.addWidget(self.lineEdit_59, 6, 4, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_2.addWidget(self.lineEdit_40, 4, 3, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_2.addWidget(self.lineEdit_24, 2, 5, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_2.addWidget(self.lineEdit_39, 4, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 0, 7, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_2.addWidget(self.lineEdit_35, 3, 7, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_2.addWidget(self.lineEdit_52, 5, 6, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_2.addWidget(self.lineEdit_46, 5, 0, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_2.addWidget(self.lineEdit_43, 4, 6, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_2.addWidget(self.lineEdit_18, 1, 8, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 0, 3, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_2.addWidget(self.lineEdit_41, 4, 4, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_2.addWidget(self.lineEdit_58, 6, 3, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout_2.addWidget(self.lineEdit_65, 7, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 0, 8, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_2.addWidget(self.lineEdit_56, 6, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 1, 4, 1, 1)
        self.lineEdit_73 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.gridLayout_2.addWidget(self.lineEdit_73, 8, 0, 1, 1)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.gridLayout_2.addWidget(self.lineEdit_74, 8, 1, 1, 1)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.gridLayout_2.addWidget(self.lineEdit_75, 8, 2, 1, 1)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.gridLayout_2.addWidget(self.lineEdit_76, 8, 3, 1, 1)
        self.lineEdit_77 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.gridLayout_2.addWidget(self.lineEdit_77, 8, 4, 1, 1)
        self.lineEdit_78 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.gridLayout_2.addWidget(self.lineEdit_78, 8, 5, 1, 1)
        self.lineEdit_79 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.gridLayout_2.addWidget(self.lineEdit_79, 8, 6, 1, 1)
        self.lineEdit_80 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.gridLayout_2.addWidget(self.lineEdit_80, 8, 7, 1, 1)
        self.lineEdit_81 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.gridLayout_2.addWidget(self.lineEdit_81, 8, 8, 1, 1)

        self.retranslateUi(Modifier)
        QtCore.QMetaObject.connectSlotsByName(Modifier)

    def retranslateUi(self, Modifier):
        _translate = QtCore.QCoreApplication.translate
        Modifier.setWindowTitle(_translate("Modifier", "Form"))


